apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: jandj-infra
  labels:
    app: backend
data:
  NODE_ENV: "production"
  PORT: "5000"
  BASE_URL: "https://your-domain.com"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
